# Generated by Django 4.2b1 on 2023-04-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('place_title',)},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Позиция'),
        ),
    ]
