# Generated by Django 4.2b1 on 2023-04-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_options_alter_image_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
